spark.driver.memory          1g
spark.executor.memory        1g
spark.executor.cores         1
spark.sql.shuffle.partitions 8
spark.ui.showConsoleProgress true
spark.hadoop.fs.defaultFS    hdfs://namenode:9000
